#!/bin/bash

# setup the test ennvironment inside this shell
. setup-sourced

xauth add examplehost1/unix:0 MIT-MAGIC-COOKIE-1 b90b0fd1cf6a0e7a2c74c00000000001
xauth add examplehost2/unix:0 . b90b0fd1cf6a0e7a2c74c00000000002
xauth add examplehost3/unix:0 . b90b0fd1cf6a0e7a2c74c00000000003

xauth list                      
xauth nlist                     
xauth list examplehost1/unix:0  
xauth nlist examplehost2/unix:0 

xauth remove examplehost1/unix:0
xauth list                      
xauth remove examplehost2/unix:0
xauth remove examplehost3/unix:0
xauth list                      

