.lavapipe-rules:
  stage: software-renderer
  rules:
    - !reference [.test, rules]
    - if: $EXTERNAL_KERNEL_TAG != null
      when: never
    - !reference [.vulkan-rules, rules]
    - !reference [.gallium-core-rules, rules]
    - changes: &lavapipe_file_list
        - src/gallium/drivers/llvmpipe/*
        - src/gallium/frontends/lavapipe/*
        - src/gallium/frontends/lavapipe/ci/gitlab-ci.yml
        - src/gallium/frontends/lavapipe/ci/gitlab-ci-inc.yml
        - src/gallium/frontends/lavapipe/ci/deqp-$DEQP_SUITE.toml
        - src/gallium/frontends/lavapipe/ci/$GPU_VERSION-fails.txt
        - src/gallium/frontends/lavapipe/ci/$GPU_VERSION-flakes.txt
        - src/gallium/frontends/lavapipe/ci/$GPU_VERSION-skips.txt
        - src/gallium/frontends/lavapipe/ci/$VK_DRIVER-skips.txt
        - src/gallium/frontends/lavapipe/ci/$GALLIUM_DRIVER-skips.txt
        - src/gallium/frontends/lavapipe/ci/$DRIVER_NAME-skips.txt
        - src/gallium/frontends/lavapipe/ci/$PIGLIT_TRACES_FILE
        - src/gallium/winsys/sw/**/*
        - src/gallium/auxiliary/draw/**/*
        - src/gallium/auxiliary/gallivm/**/*
      when: on_success

.lavapipe-manual-rules:
  stage: software-renderer-postmerge
  extends: .no-auto-retry
  rules:
    - !reference [.test, rules]
    - !reference [.vulkan-manual-rules, rules]
    - !reference [.gl-manual-rules, rules]
    - changes: *lavapipe_file_list
      when: manual

.lavapipe-test:
  stage: software-renderer
  extends:
    - .test-vk
    - .lavapipe-rules
  variables:
    VK_DRIVER: lvp
    LVP_POISON_MEMORY: "1"
    HWCI_START_WESTON: 1
