C_SOURCES := \
	virgl_buffer.c \
	virgl_context.c \
	virgl_context.h \
	virgl_encode.c \
	virgl_encode.h \
	virgl_public.h \
	virgl_query.c \
	virgl_resource.c \
	virgl_resource.h \
	virgl_screen.c \
	virgl_screen.h \
	virgl_staging_mgr.c \
	virgl_staging_mgr.h \
	virgl_streamout.c \
	virgl_texture.c \
	virgl_tgsi.c \
	virgl_transfer_queue.c \
	virgl_transfer_queue.h \
	virgl_winsys.h
