.venus-rules:
  stage: layered-backends
  rules:
    - !reference [.test, rules]
    - !reference [.lavapipe-rules, rules]
    - changes: &venus_file_list
      - src/virtio/**/*
      when: on_success


.venus-lavapipe-test:
  extends:
    - .test-vk
    - .venus-rules
  variables:
    VK_DRIVER: virtio
    CROSVM_GALLIUM_DRIVER: "llvmpipe"
    CROSVM_VK_DRIVER: "lvp"
    CROSVM_GPU_ARGS: "vulkan=true,gles=false,backend=virglrenderer,egl=true,surfaceless=true,fixed-blob-mapping=false"
