C_SOURCES := \
	entrypoint.c \
	entrypoint.h \
	h264d.c \
	h264d.h \
	h264dprc.c \
	h264dprc.h \
	h264dinport.c \
	h264dinport.h \
	h264dinport_decls.h \
	h264e.c \
	h264e.h \
	h264eprc.c \
	h264eprc.h \
	h264einport.h \
	h264einport.c \
	h264einport_decls.h \
	h264einport.h \
	h264eoutport.c \
	h264eoutport_decls.h \
	h264eoutport.h \
	names.h
