# escape=`

FROM mcr.microsoft.com/windows:1809

# Make sure any failure in PowerShell scripts is fatal
SHELL ["powershell", "-ExecutionPolicy", "RemoteSigned", "-Command", "$ErrorActionPreference = 'Stop';"]
ENV ErrorActionPreference='Stop'

COPY mesa_deps_vs2019.ps1 C:\
RUN C:\mesa_deps_vs2019.ps1

COPY mesa_deps_build.ps1 C:\
RUN C:\mesa_deps_build.ps1
