# escape=`

ARG base_image
FROM ${base_image}

COPY mesa_deps_build.ps1 C:\
RUN C:\mesa_deps_build.ps1

# When building, `--isolation=process` can leverage all cores and memory
# docker build --isolation=process -f .\Dockerfile_build -t mesa_dep --build-arg base_image=mesa_vs .

