ifneq ($(NORELDBG),1)
$(error NORELDBG should have been set to 1)
endif
ifneq ($(IS64),0)
$(error IS64 should have been set to 0, buld is independent on 64-bit)
endif

srcdir=.

format_srgb.c: format_srgb.py
	python $(srcdir)/format_srgb.py > $@

format/u_format_table.c: $(srcdir)/format/u_format_table.py $(srcdir)/format/u_format.csv
	python $(srcdir)/format/u_format_table.py $(srcdir)/format/u_format.csv > $@

