
VULKAN_WSI_FILES := \
	wsi/wsi_common.h \
	wsi/wsi_common_queue.h

VULKAN_WSI_WAYLAND_FILES := \
	wsi/wsi_common_wayland.c \
	wsi/wsi_common_wayland.h

VULKAN_WSI_WAYLAND_GENERATED_FILES := \
	wsi/wayland-drm-protocol.c \
	wsi/wayland-drm-client-protocol.h

VULKAN_WSI_X11_FILES := \
	wsi/wsi_common_x11.c \
	wsi/wsi_common_x11.h

VULKAN_UTIL_FILES := \
	util/vk_alloc.h \
	util/vk_util.c \
	util/vk_util.h

VULKAN_UTIL_GENERATED_FILES := \
	util/vk_enum_to_str.c \
	util/vk_enum_to_str.h
