ifneq ($(NORELDBG),1)
$(error NORELDBG should have been set to 1)
endif

PUBLIC_FILES = \
	..\fontconfig\fontconfig.h \
	fcdeprecate.h \
	..\fontconfig\fcprivate.h

PUBLIC_FT_FILES = \
	..\fontconfig\fcfreetype.h

fcalias.h fcaliastail.h: makealias.py $(PUBLIC_FILES)
	python makealias.py . fcalias.h fcaliastail.h $(PUBLIC_FILES)

fcftalias.h fcftaliastail.h: makealias.py $(PUBLIC_FT_FILES)
	python makealias.py . fcftalias.h fcftaliastail.h $(PUBLIC_FT_FILES)

