C_SOURCES := \
	pan_assemble.c \
	pan_blend_cso.c \
	pan_blend_cso.h \
	pan_blit.c \
	pan_cmdstream.c \
	pan_cmdstream.h \
	pan_compute.c \
	pan_context.c \
	pan_context.h \
	pan_job.c \
	pan_job.h \
	pan_public.h \
	pan_resource.c \
	pan_resource.h \
	pan_screen.c \
	pan_screen.h
