// freedreno specific driconf options

DRI_CONF_SECTION_MISCELLANEOUS
   DRI_CONF_DISABLE_CONSERVATIVE_LRZ(false)
DRI_CONF_SECTION_END

DRI_CONF_SECTION_DEBUG
   DRI_CONF_DISABLE_THROTTLING(false)
   DRI_CONF_DUAL_COLOR_BLEND_BY_LOCATION(false)
DRI_CONF_SECTION_END
