ifneq ($(NORELDBG),1)
$(error NORELDBG should have been set to 1)
endif
ifneq ($(IS64),0)
$(error IS64 should have been set to 0, buld is independent on 64-bit)
endif

srcdir=.

options.h: t_options.h
	python $(srcdir)/gen_xmlpool.py $(srcdir)/t_options.h $(srcdir) > options.h

