CSRCS = \
	present.c \
	present_event.c \
	present_execute.c \
	present_fake.c \
	present_fence.c \
	present_notify.c \
	present_request.c \
	present_scmd.c \
	present_screen.c \
	present_vblank.c \
	present_wnmd.c

LIBRARY=libpresent

DEFINES += PIXMAN_API=
