Import('*')

env = env.Clone()

env.Prepend(CPPPATH = [
    '../../../compiler/nir',
    ])

env.MSVC2013Compat()

softpipe = env.ConvenienceLibrary(
	target = 'softpipe',
	source = env.ParseSourceList('Makefile.sources', 'C_SOURCES')
	)

env.Alias('softpipe', softpipe)

Export('softpipe')
