
VULKAN_WSI_FILES := \
	wsi_common.h \
	wsi_common_queue.h

VULKAN_WSI_WAYLAND_FILES := \
	wsi_common_wayland.c \
	wsi_common_wayland.h

VULKAN_WSI_X11_FILES := \
	wsi_common_x11.c \
	wsi_common_x11.h