Import('*')

env = env.Clone()

env.MSVC2013Compat()

env.Prepend(CPPPATH = [
    '#include'
])

if env['drm']:
    env.PkgUseModules('DRM')
    env.Append(CPPDEFINES = ['HAVE_LIBDRM'])

# parse Makefile.sources
sources = env.ParseSourceList('Makefile.sources', 'LOADER_C_FILES')

libloader = env.ConvenienceLibrary(
    target = 'libloader',
    source = sources,
)

env.Alias('libloader', libloader)
Export('libloader')
